# LSTM Stock Predictor Using Fear and Greed Index

In this notebook, you will build and train a custom LSTM RNN that uses a 10 day window of Bitcoin fear and greed index values to predict the 11th day closing price. 

You will need to:

1. Prepare the data for training and testing
2. Build and train a custom LSTM RNN
3. Evaluate the performance of the model

## Data Preparation

In this section, you will need to prepare the training and testing data for the model. The model will use a rolling 10 day window to predict the 11th day closing price.

You will need to:
1. Use the `window_data` function to generate the X and y values for the model.
2. Split the data into 70% training and 30% testing
3. Apply the MinMaxScaler to the X and y values
4. Reshape the X_train and X_test data for the model. Note: The required input format for the LSTM is:

```python
reshape((X_train.shape[0], X_train.shape[1], 1))
```

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
%matplotlib

Using matplotlib backend: MacOSX


In [3]:
# Set the random seed for reproducibility
# Note: This is for the homework solution, but it is good practice to comment this out and run multiple experiments to evaluate your model
from numpy.random import seed
seed(1)
from tensorflow import random
random.set_seed(2)

In [4]:
# Load the fear and greed sentiment data for Bitcoin
df = pd.read_csv('btc_sentiment.csv', index_col="date", infer_datetime_format=True, parse_dates=True)
df = df.drop(columns="fng_classification")
df.head()

fng_value
date                  
2019-07-29          19
2019-07-28          16
2019-07-27          47
2019-07-26          24
2019-07-25          42

In [5]:
# Load the historical closing prices for Bitcoin
df2 = pd.read_csv('btc_historic.csv', index_col="Date", infer_datetime_format=True, parse_dates=True)['Close']
df2 = df2.sort_index()
df2.tail()

Date
2019-07-25    9882.429688
2019-07-26    9847.450195
2019-07-27    9478.320313
2019-07-28    9531.769531
2019-07-29    9529.889648
Name: Close, dtype: float64

In [6]:
# Join the data into a single DataFrame
df = df.join(df2, how="inner")
df.tail()

fng_value        Close
2019-07-25          42  9882.429688
2019-07-26          24  9847.450195
2019-07-27          47  9478.320313
2019-07-28          16  9531.769531
2019-07-29          19  9529.889648

In [7]:
df.head()

fng_value        Close
2018-02-01          30  9114.719727
2018-02-02          15  8870.820313
2018-02-03          40  9251.269531
2018-02-04          24  8218.049805
2018-02-05          11  6937.080078

In [8]:
# This function accepts the column number for the features (X) and the target (y)
# It chunks the data up with a rolling window of Xt-n to predict Xt
# It returns a numpy array of X any y
def window_data(df, window, feature_col_number, target_col_number):
    X = []
    y = []
    for i in range(len(df) - window - 1):
        features = df.iloc[i:(i + window), feature_col_number]
        target = df.iloc[(i + window), target_col_number]
        X.append(features)
        y.append(target)
    return np.array(X), np.array(y).reshape(-1, 1)

In [9]:
# Predict Closing Prices using a 10 day window of previous fng values
# Then, experiment with window sizes anywhere from 1 to 10 and see how the model performance changes
window_size = 5

# Column index 0 is the 'fng_value' column
# Column index 1 is the `Close` column
feature_column = 0
target_column = 1
X, y = window_data(df, window_size, feature_column, target_column)

In [10]:
# Use 70% of the data for training and the remaineder for testing
split = int(0.7 *len(X))
X_train = X[: split]
X_test = X[split :]
y_train = y[: split]
y_test = y[split :]

In [11]:
# Use the MinMaxScaler to scale data between 0 and 1.
X_scaler = MinMaxScaler()
X_scaler.fit(X_train)

# Scale the features training and testing sets
X_train = X_scaler.transform(X_train)
X_test = X_scaler.transform(X_test)

# Fit the MinMaxScaler object with the training target data y_train
y_scaler = MinMaxScaler()
y_scaler.fit(y_train)

# Scale the target training and testing sets
y_train = y_scaler.transform(y_train)
y_test = y_scaler.transform(y_test)

In [12]:
print(X_train)


[[0.33333333 0.10606061 0.48484848 0.24242424 0.04545455]
 [0.10606061 0.48484848 0.24242424 0.04545455 0.        ]
 [0.48484848 0.24242424 0.04545455 0.         0.42424242]
 ...
 [0.48484848 0.57575758 0.45454545 0.60606061 0.60606061]
 [0.57575758 0.45454545 0.60606061 0.60606061 0.53030303]
 [0.45454545 0.60606061 0.60606061 0.53030303 0.53030303]]


In [13]:
# Reshape the features for the model
X_train = X_train.reshape(X_train.shape[0], X_train.shape[1],1)
X_train.shape

(375, 5, 1)

---

## Build and Train the LSTM RNN

In this section, you will design a custom LSTM RNN and fit (train) it using the training data.

You will need to:
1. Define the model architecture
2. Compile the model
3. Fit the model to the training data

### Hints:
You will want to use the same model architecture and random seed for both notebooks. This is necessary to accurately compare the performance of the FNG model vs the closing price model. 

In [14]:
# Build the LSTM model. 
# The return sequences need to be set to True if you are adding additional LSTM layers, but 
# You don't have to do this for the final layer. 
# Note: The dropouts help prevent overfitting
# Note: The input shape is the number of time steps and the number of indicators
# Note: Batching inputs has a different input shape of Samples/TimeSteps/Features

model = Sequential()
number_units = 10
dropout_fraction = 0.4

# add layers
# layer 1
model.add(LSTM(units=number_units, return_sequences=True, input_shape=(X_train.shape[1], 1)))
model.add(Dropout(dropout_fraction))

# Layer 2
model.add(LSTM(units=number_units, return_sequences=True))
model.add(Dropout(dropout_fraction))

# Layer 3
model.add(LSTM(units=number_units))
model.add(Dropout(dropout_fraction))

# Output layer
model.add(Dense(1))

2022-02-07 01:17:41.964330: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [15]:
# Compile the model
model.compile(loss = "mean_squared_error", optimizer = "adam", metrics=['mse'])

In [16]:
# Summarize the model
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 5, 10)             480       
                                                                 
 dropout (Dropout)           (None, 5, 10)             0         
                                                                 
 lstm_1 (LSTM)               (None, 5, 10)             840       
                                                                 
 dropout_1 (Dropout)         (None, 5, 10)             0         
                                                                 
 lstm_2 (LSTM)               (None, 10)                840       
                                                                 
 dropout_2 (Dropout)         (None, 10)                0         
                                                                 
 dense (Dense)               (None, 1)                 1

In [17]:
# Train the model
# Use at least 10 epochs
# Do not shuffle the data
# Experiement with the batch size, but a smaller batch size is recommended
model.fit(X_train, y_train, epochs=15, shuffle=False, batch_size=2, verbose=1)

Epoch 1/15
188/188 [==============================] - 7s 8ms/step - loss: 0.1013 - mse: 0.1013
Epoch 2/15
188/188 [==============================] - 2s 10ms/step - loss: 0.0670 - mse: 0.0670
Epoch 3/15
188/188 [==============================] - 2s 10ms/step - loss: 0.0682 - mse: 0.0682
Epoch 4/15
188/188 [==============================] - 2s 10ms/step - loss: 0.0647 - mse: 0.0647
Epoch 5/15
188/188 [==============================] - 2s 9ms/step - loss: 0.0663 - mse: 0.0663
Epoch 6/15
188/188 [==============================] - 2s 9ms/step - loss: 0.0623 - mse: 0.0623
Epoch 7/15
188/188 [==============================] - 2s 10ms/step - loss: 0.0552 - mse: 0.0552
Epoch 8/15
188/188 [==============================] - 2s 10ms/step - loss: 0.0577 - mse: 0.0577
Epoch 9/15
188/188 [==============================] - 2s 11ms/step - loss: 0.0535 - mse: 0.0535
Epoch 10/15
188/188 [==============================] - 2s 10ms/step - loss: 0.0547 - mse: 0.0547
Epoch 11/15
188/188 [=====================

---

## Model Performance

In this section, you will evaluate the model using the test data. 

You will need to:
1. Evaluate the model using the `X_test` and `y_test` data.
2. Use the X_test data to make predictions
3. Create a DataFrame of Real (y_test) vs predicted values. 
4. Plot the Real vs predicted values as a line chart

### Hints
Remember to apply the `inverse_transform` function to the predicted and y_test values to recover the actual closing prices.

In [18]:
# Evaluate the model
model.evaluate(X_test, y_test)

6/6 [==============================] - 1s 4ms/step - loss: 0.1056 - mse: 0.1056


[0.10556554049253464, 0.10556554049253464]

In [19]:
# Make some predictions
predicted = model.predict(X_test)

In [24]:
# Recover the original prices instead of the scaled version
predicted_prices = y_scaler.inverse_transform(predicted)
real_prices = y_scaler.inverse_transform(y_test.reshape(-1, 1))

In [27]:
# Create a DataFrame of Real and Predicted values
stocks = pd.DataFrame({
    "Real": real_prices.ravel(),
    "Predicted": predicted_prices.ravel()
}, index = df.index[-len(real_prices): ]) 
stocks.head()

Real    Predicted
2019-02-18  3670.919922  5922.997559
2019-02-19  3912.570068  5839.307617
2019-02-20  3924.239990  5829.596191
2019-02-21  3974.050049  5969.924805
2019-02-22  3937.040039  6148.367188

In [28]:
# Plot the real vs predicted values as a line chart
stocks.plot(xlabel="Months of 2019", ylabel="Close Price($)", title="Real vs. Predicted Bitcoin Value in USD");

objc[25138]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff93d1e3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x14fc1bf50). One of the two will be used. Which one is undefined.
